---
version: "{build}"
clone_depth: 1
install:
  - SET PATH=C:\Ruby22\bin;%PATH%
  - ruby --version
build: off
test_script:
  - ruby test.rb
  - ruby  -e "puts" | ruby -n -e 'm = Kernel.private_instance_methods(false).grep(/^chop$/); print m.map { |x| x.to_s }.join("")'
